const a = [
{title:"신청 링크가 9px 이모지로 축소(엔드 피크)",priority:"critical",evidence:"data/all.json 84431강좌 100%가 12번필드에 직접 신청 URL 보유하나, index.html:1455 테이블 맨끝 fontSize 9 사슬 이모지 하나로만 노출. 강좌명(4번,1443행) 클릭은 센터모달만 열고 신청 핸들러 없음. 최종 전환 행동이 화면 최소 9px(권장 44px 미달) 우측끝 저대비 타겟.",principle:"피크엔드(엔드=신청 성공) + Fitts(44px) + Jakob",recommendation:"강좌명 셀 onClick에 stopPropagation 후 window.open(12번필드,_blank,noopener)+accent색, 행끝 사슬을 신청 텍스트버튼(28-32px,accent)으로 승격. 센터모달 진입은 센터명셀(1437)에만.",before_after:"BEFORE 맨끝 9px 정확탭(모바일 거의 불가). AFTER 강좌명 1탭으로 신청페이지.",effort:"S",regression_risk:"low"},
{title:"센터상세 모달이 막다른 길",priority:"critical",evidence:"센터모달(index.html:1614-1663)은 카드(969)·테이블센터셀(1437)·통계TOP10(1228) 공통 종착지인데 강좌리스트(1644행)에 12번필드(신청)·mapLink(주소) 컬럼이 없어 신청 출구 0개. 헤더 전화(1624)는 데이터 23.7%만 보유로 대부분 빈칸, 주소(1621)도 텍스트뿐 카카오맵 링크 아님.",principle:"피크엔드(발견직후=신청직전) + Jakob",recommendation:"모달 강좌테이블에 신청 컬럼 추가(12번필드 a태그 target blank noopener). 주소(1621)를 기존 mapLink함수(904)로 감싸 카카오맵 길찾기화. 둘 다 기존 함수·필드 재사용.",before_after:"BEFORE 신청·길찾기 없어 테이블로 되돌아감. AFTER 강좌 옆 신청·길찾기 바로.",effort:"S",regression_risk:"low"},
{title:"첫 검색 성공(코어 피크)에 성공 피드백 없음",priority:"high",evidence:"OSRM 이동시간이 처음 실현되는 피크인데 applyAddr(627-646) 완료시 회색텍스트(645)만, 화면엔 fontSize 10 muted 한 줄(1045). 진행률도 평문(639). showT 토스트(677,2.5초) 인프라 있는데 미사용. 결과 카운트(1305)도 정적.",principle:"피크엔드(첫 가치 실현) + 인터랙션 피드백 + 트랜지션 150-300ms",recommendation:"applyAddr 완료직후(644) showT 1줄 추가(centers.length곳 이동시간 계산완료). 카운트(1305)에 기존 키프레임(cardFadeIn,slideUp) 재사용 0.3초 accent 펄스.",before_after:"BEFORE 로딩 후 회색 한 줄. AFTER 토스트+숫자 펄스로 성취감 각인.",effort:"S",regression_risk:"none"},
{title:"게이미피케이션 5중 플로팅 런처가 피크 압도",priority:"high",evidence:"v4-v8 독립 런처 사방 주입: v6 하단중앙(v6:934,973) v7 우상단(v7:915) v8 좌상단하단(v8:1303) v4·v5 인라인(v4:301,v5:1143). 추천·증명서·퀴즈·업적 등 버튼 50여개. 로드 2-3초후 v6/v7/v8 라벨 토글 3개가 검색-발견-신청 동선 위를 덮음. 정작 신청 버튼은 없음.",principle:"피크엔드(곁가지 과잉이 피크 가림) + Hick + 첫화면 3초",recommendation:"삭제 대신 접힘·집결. v7·v8처럼 초기 display none을 v6에도 적용, 세 컨테이너 position을 우하단 1곳 통일(right 12px+bottom 단계값), 라벨 v6/v7/v8을 메뉴/점으로.",before_after:"BEFORE 사방 토글이 동선 가림. AFTER 우하단 접힘, 첫화면 검색·결과·신청만 또렷.",effort:"M",regression_risk:"medium"}
];
const s = JSON.stringify(a);
let out = '';
for (const ch of s) { const c = ch.codePointAt(0); out += c > 127 ? '\\u' + c.toString(16).padStart(4, '0') : ch; }
require('fs').writeFileSync(__dirname + '/_f4_escaped.txt', out);
console.log('raw chars:', s.length, 'escaped chars:', out.length, 'reparse:', JSON.parse(out).length);
