# -*- coding: utf-8 -*-
import json
findings=[
{"title":"라이브 사이트에 강사 실명 PII 약 1.6만건이 백업 JSON으로 공개 노출, privacy 작업 전체 무력화","priority":"critical","evidence":"git-tracked 백업/스냅샷이 라이브로 그대로 서빙됨. 실측으로 bsy522-dot.github.io 의 data/all_backup_20260501.json 경로가 HTTP 200 응답하고 첫 레코드 10번째 필드에 실명 이오숙 포함. 파일별 고유 강사명 수는 all_backup_20260403.json 4776, all_backup_20260501.json 3059, courses_live.json 3378, courses_all_backup.json 3507, lotte_live.json 1510, hp_live.json 481 등 8개 파일 합계 약 1.6만명. 반면 라이브 all.json은 10번째 필드가 빈 문자열로 정상 제거됨. index.html 663행이 로드하는 유일한 데이터 파일이 그 all.json. 모든 백업은 commit fff7894에 커밋됨.","principle":"개인정보보호 PII 노출 0 및 데이터 거버넌스. 제거는 모든 사본에 적용되어야 유효","recommendation":"앱이 실제 로드하는 파일은 data/all.json 과 data/center_coords.json 2개뿐(index.html 663-664행, sw.js 15-16행 확인). PII 포함 백업 전부 git 추적에서 제거: all_backup_20260403.json, all_backup_20260501.json, courses_all.json, courses_all_backup.json, courses_live.json, courses_v2.json, lotte_live.json, hp_live.json, emart_live.json, full_yuah.json, parsed_courses.json, excel_preview.json, meta.json, crawl_meta.json 그리고 courses 계열 js.txt 와 final_js.txt. 회사 룰대로 삭제 대신 _deleted_files로 이동 후 git rm cached. 주의: working tree 제거만으로 라이브 서빙은 즉시 중단되나 git history엔 잔존하므로 추후 history 정리를 별도 2단계 작업으로 진행 권고.","before_after":"Before 라이브 URL에서 강사 실명 약 1.6만건 다운로드 가능으로 privacy.html 과 강사명 제거 작업이 무의미. After all.json 실명 공란 1개만 공개되어 PII 노출 0건, 앱 동작 100퍼센트 동일.","effort":"S","regression_risk":"none"},
{"title":"v7_patch.js에 가짜 평점용 강사 실명 배열 INSTRUCTORS 12명이 운영 코드에 상주","priority":"high","evidence":"v7_patch.js 172-185행 INSTRUCTORS 배열에 실명 12명과 허위 평점 리뷰수. 예로 김수연 평점 4.8 리뷰 42. index.html 1791행이 v7_patch.js 로드, showInstructorRating 함수 v7 187행부터가 강사 평점 모달로 렌더하며 201행에서 이름과 강사를 표시. 강사명 제거 정책과 정면 충돌이고 동명이인 명예 정보 리스크. 데이터는 임의값 가짜인데 사용자에게 실제 평점처럼 노출. 이 배열은 v7 평점 모달 전용으로 타 파일 미참조.","principle":"데이터 진위 즉 가짜 사회적 증거 금지와 개인정보. 상용 제품의 fabricated rating은 신뢰 법적 리스크","recommendation":"최소변경 외과적 2안. A안 권장은 showInstructorRating 호출 진입점 메뉴 버튼 1곳만 주석 처리해 모달 미노출, 배열 정의는 두되 화면 도달 불가. B안은 기능 유지가 필요하면 실명을 익명 라벨로 치환하여 김수연을 수영 강사 A 식으로 12개 문자열만 교체하고 평점 리뷰는 유지. 어느 쪽도 타 기능 무영향.","before_after":"Before 실명 12명과 허위 4.8점 42리뷰가 강사 평점 화면에 실데이터처럼 표시. After A는 해당 화면 비노출이고 나머지 기능 무영향. After B는 수영 강사 A 등 익명 표시로 PII 진위 리스크 동시 해소.","effort":"S","regression_risk":"low"},
{"title":"타사 홈플러스 원본 HTML 7개와 API 응답 HTML이 git-tracked 라이브로 저작권 스크래핑 흔적 노출","priority":"high","evidence":"data 폴더의 hp 강동점 hp 금천점 hp 서울남현점 hp 신도림점 hp 영등포점 hp 잠실점 hp 합정점 html 7개가 각 약 197에서 200KB, 추가로 hp_api_response.html 42KB. 총 약 1.4MB 홈플러스 문화센터 원본 마크업과 내부 API 응답이 공개 커밋됨. 앱 코드 미참조로 로드 파일은 all.json 과 center_coords.json 뿐. 라이브 도메인에서 직접 fetch 가능하여 타사 페이지 전체를 재배포하는 셈이고 크롤링 방식 엔드포인트가 외부에 노출.","principle":"법적 리스크 회피 즉 타사 콘텐츠 재배포 금지와 공격면 최소화. 출시 차단 요인급","recommendation":"hp 계열 html 7개와 hp_api_response.html을 _deleted_files로 이동 후 git rm cached. 크롤링 원본은 로컬 crawlers 작업 폴더에만 보관하고 배포 리포 미포함. 동일 성격 스크린샷 7개인 lotte_shopping_search.png 606KB lotte_shopping_culture.png 204KB emart_mobile_home.png 166KB 등 합 1.1MB도 함께 제거.","before_after":"Before 타사 원본 HTML 1.4MB와 캡처 1.1MB가 라이브에 공개. After 제거로 저작권 공격면 용량 동시 축소되고 앱 동작 불변.","effort":"S","regression_risk":"none"},
{"title":"배포 리포 data 폴더에 앱 미사용 정크 약 63.7MB 52파일 누적으로 빌드 캐시 전송 낭비와 유지보수 혼선","priority":"medium","evidence":"git ls-files data 결과 54파일 중 앱 로드는 all.json 과 center_coords.json 2개뿐(index.html 663-664행). 나머지 52파일 합계 63.7MB로 백업 스냅샷 JSON 60.7MB, 중간 산출 txt 1.8MB, regions 19개 JSON은 앱 미사용이며 v5_patch.js의 regions는 localStorage 통계 객체일 뿐 data 폴더 regions와 무관, 그 외 meta.json crawl_meta.json region_check txt 등. 라이브 all.json 자체도 27MB라 초기 로드 부담이 큰데 정크가 리포 용량 clone 페이지 빌드시간을 키움.","principle":"단순성 유지보수성 YAGNI. 배포 산출물엔 런타임 필수만 두어야 하며 정크는 어느 게 진짜 데이터인지 혼동 유발","recommendation":"위 3개 finding 제거 대상을 합치면 사실상 data 폴더는 all.json 과 center_coords.json 2개만 남음으로 회귀 0퍼센트. 일괄로 _deleted_files 하위 munsen_data_junk 폴더로 이동 후 git rm cached 하여 1커밋. regions 디렉터리도 미사용이면 동일 처리하되 향후 지역별 분할 로드 계획이 있으면 보류, 현재 코드엔 로더 없음.","before_after":"Before data 폴더 64MB 54파일로 진짜 백업 정크 혼재. After data 폴더 약 27MB 2파일로 리포 경량화 혼선 제거되고 런타임 100퍼센트 동일.","effort":"S","regression_risk":"none"},
{"title":".gitignore가 존재하나 data 정크와 크롤링 산출물을 전혀 차단 못 해 재발 보장","priority":"medium","evidence":".gitignore는 실재하며 1행부터 10행에 claude 폴더 bak baseline xssbak node_modules dist src app.jsx 만 제외. 빌드와 백업 확장자는 막지만 data 폴더의 all_backup json, live json, hp html, png, js.txt 패턴은 무방비. 그 결과 이번 PII 타사HTML 63MB 정크가 전부 커밋됨. 한 번 정리해도 다음 크롤링 산출물이 동일하게 재유입될 구조.","principle":"재발 방지 즉 프로세스로 실수 차단. 비개발자 운영일수록 gitignore 가드레일 필수","recommendation":".gitignore에 외과적 패턴 추가하되 기존 유지. 추가 패턴은 data 슬래시 backup json 와 all_backup 패턴, live json, courses json, hp html, js.txt, png, full_yuah parsed_courses excel_preview meta crawl_meta. 단 화이트리스트로 필수 2개를 보호 즉 부정 패턴으로 all.json 과 center_coords.json 은 제외에서 빼서 계속 추적. 이렇게 하면 향후 크롤링 산출물이 자동 무시되어 PII 정크 재유입 차단.","before_after":"Before gitignore가 data 정크를 못 막아 매 크롤링마다 백업 실명 타사HTML 재커밋 위험. After 패턴과 화이트리스트로 필수 2파일만 추적하여 실명 정크 재유입 0, 기존 추적 파일은 finding 1 3 4의 git rm으로 처리.","effort":"S","regression_risk":"none"}
]
with open(r"D:\AI\03_신사업\문센파인더\app\.claude\worktrees\improve-20260610\_findings_escaped.txt","w",encoding="ascii") as f:
    f.write(json.dumps(findings, ensure_ascii=True))
print("OK len=", len(json.dumps(findings, ensure_ascii=True)))
